/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteVentanas;

import javax.swing.JOptionPane;

/**
 *
 * @author MARTHA
 */
public class ConstruirArma extends javax.swing.JFrame {
    private int contadorPiedra=0,contadorCristal=0,contadorHilo=0,contadorMadera=0,contadorHacha=0,
            contadorMartillo=0,contadorRed=0, contadorArco=0, contadorTelescopio;    /**
     * Creates new form ConstruirArma
     */
    public ConstruirArma(int piedra, int cristal, int hilo, int madera, int hacha, int martillo,int arco,int telescopio,int red) {
        
        contadorPiedra = piedra;
        contadorCristal = cristal;
        contadorHilo = hilo;
        contadorMadera = madera;
        contadorHacha = hacha;
        contadorMartillo = martillo;
        contadorArco = arco;
        contadorTelescopio = telescopio;
        contadorRed = red;
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Arco = new javax.swing.JLabel();
        Telescopio = new javax.swing.JLabel();
        BotonTelescopio = new javax.swing.JButton();
        EtiquetaRequisitosTelescopio = new javax.swing.JLabel();
        PiedraHacha = new javax.swing.JLabel();
        HiloHacha = new javax.swing.JLabel();
        MaderaHacha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();
        CantidadRed = new javax.swing.JLabel();
        MaderaMartillo = new javax.swing.JLabel();
        HiloMartillo = new javax.swing.JLabel();
        PiedraMartillo = new javax.swing.JLabel();
        EtiquetaRequisitosArco = new javax.swing.JLabel();
        BotonArco = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CantidadArco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BotonRed = new javax.swing.JButton();
        Red = new javax.swing.JLabel();
        EtiquetaRequisitosRed = new javax.swing.JLabel();
        PiedraMartillo2 = new javax.swing.JLabel();
        HiloHacha1 = new javax.swing.JLabel();
        MaderaHacha1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CantidadTelescopio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Arco.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Arco.setText("Arco");
        jPanel1.add(Arco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        Telescopio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Telescopio.setText("Telescopio");
        jPanel1.add(Telescopio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        BotonTelescopio.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Red.jpg")); // NOI18N
        BotonTelescopio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonTelescopioMouseClicked(evt);
            }
        });
        jPanel1.add(BotonTelescopio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 105, 110));

        EtiquetaRequisitosTelescopio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaRequisitosTelescopio.setText("Requisitos:");
        jPanel1.add(EtiquetaRequisitosTelescopio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        PiedraHacha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PiedraHacha.setText("Piedra = 1");
        jPanel1.add(PiedraHacha, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 168, -1, -1));

        HiloHacha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HiloHacha.setText("Martillo = 1");
        jPanel1.add(HiloHacha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        MaderaHacha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaderaHacha.setText("Madera = 4");
        jPanel1.add(MaderaHacha, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cantidad: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        BotonRegresar.setBackground(new java.awt.Color(204, 204, 255));
        BotonRegresar.setText("Regresar");
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, -1, -1));

        CantidadRed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadRed.setText("0");
        if(contadorRed==0){
            CantidadRed.setText(""+(contadorRed));
        }else{
            CantidadRed.setText(""+(contadorRed-1));
        }
        jPanel1.add(CantidadRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 23, -1));

        MaderaMartillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaderaMartillo.setText("Madera = 4");
        jPanel1.add(MaderaMartillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        HiloMartillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HiloMartillo.setText("Hilo = 1");
        jPanel1.add(HiloMartillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        PiedraMartillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PiedraMartillo.setText("Cristal = 1");
        jPanel1.add(PiedraMartillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        EtiquetaRequisitosArco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaRequisitosArco.setText("Requisitos:");
        jPanel1.add(EtiquetaRequisitosArco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        BotonArco.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Arco.jpg")); // NOI18N
        BotonArco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonArcoMouseClicked(evt);
            }
        });
        jPanel1.add(BotonArco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 105, 110));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Cantidad: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        CantidadArco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadArco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadArco.setText("0");
        if(contadorArco==0){
            CantidadArco.setText(""+(contadorArco));
        }else{
            CantidadArco.setText(""+(contadorArco-1));
        }
        jPanel1.add(CantidadArco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 20, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fabricar Arma");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 470, -1));

        BotonRed.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Telescopio.jpg")); // NOI18N
        BotonRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRedMouseClicked(evt);
            }
        });
        jPanel1.add(BotonRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 105, 110));

        Red.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Red.setText("Red");
        jPanel1.add(Red, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        EtiquetaRequisitosRed.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaRequisitosRed.setText("Requisitos:");
        jPanel1.add(EtiquetaRequisitosRed, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        PiedraMartillo2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PiedraMartillo2.setText("Hilo = 4");
        jPanel1.add(PiedraMartillo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        HiloHacha1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HiloHacha1.setText("Madera = 2");
        jPanel1.add(HiloHacha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        MaderaHacha1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaderaHacha1.setText("Martillo = 1");
        jPanel1.add(MaderaHacha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Cantidad: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        CantidadTelescopio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadTelescopio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadTelescopio.setText("0");
        if(contadorTelescopio==0){
            CantidadTelescopio.setText(""+(contadorTelescopio));
        }else{
            CantidadTelescopio.setText(""+(contadorTelescopio-1));
        }
        jPanel1.add(CantidadTelescopio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 23, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTelescopioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTelescopioMouseClicked
        // TODO add your handling code here:
        
        if(contadorCristal>=1 && contadorMadera>=2 && contadorMartillo>=1){
            
            if(contadorTelescopio>1){
                JOptionPane.showMessageDialog(null, "No puede Crear mas de 1 Telescopio");
            }else{
                
                contadorCristal-=1;
                contadorMadera-=2;
                contadorMartillo-=1;
                contadorTelescopio+=1;
                JOptionPane.showMessageDialog(null,"Telescopio Creado");
            }

            CantidadTelescopio.setText(""+contadorTelescopio);
        }else{
            JOptionPane.showMessageDialog(null,"No tiene Requisitos suficientes para crear el Telescopio");
        }
        
        

    }//GEN-LAST:event_BotonTelescopioMouseClicked

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        // TODO add your handling code here:

        MenuPrincipal principal = new MenuPrincipal(contadorPiedra,contadorCristal,contadorMadera,contadorHilo,contadorArco,contadorMartillo,contadorHacha,contadorTelescopio,contadorRed);
        dispose();
        principal.setVisible(true);

    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonArcoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonArcoMouseClicked
        // TODO add your handling code here:
        if(contadorHilo>=1 && contadorMadera>=4){
            
            if(contadorArco>1){
                JOptionPane.showMessageDialog(null, "No puede Crear mas de 1 arco");
            }else{
                
                contadorHilo-=1;
                contadorMadera-=4;
                contadorArco+=1;
                JOptionPane.showMessageDialog(null,"Arco Creado");
            }

            CantidadArco.setText(""+contadorArco);
        }else{
            JOptionPane.showMessageDialog(null,"No tiene Requisitos suficientes para crear el Arco");
        }

       

    }//GEN-LAST:event_BotonArcoMouseClicked

    private void BotonRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRedMouseClicked
        // TODO add your handling code here:
        
        if(contadorHilo>=4 && contadorMadera>=2 && contadorMartillo>=1){
            
            if(contadorArco>1){
                JOptionPane.showMessageDialog(null, "No puede Crear mas de 2 red");
            }else{
                
                contadorHilo-=4;
                contadorMadera-=2;
                contadorMartillo-=1;
                contadorRed+=1;
                JOptionPane.showMessageDialog(null,"Red Creada");
            }

            CantidadRed.setText(""+contadorRed);
        }else{
            JOptionPane.showMessageDialog(null,"No tiene Requisitos suficientes para crear la Red");
        }
        
    }//GEN-LAST:event_BotonRedMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConstruirArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConstruirArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConstruirArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConstruirArma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConstruirArma(0,0,0,0,0,0,0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arco;
    private javax.swing.JButton BotonArco;
    private javax.swing.JButton BotonRed;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton BotonTelescopio;
    private javax.swing.JLabel CantidadArco;
    private javax.swing.JLabel CantidadRed;
    private javax.swing.JLabel CantidadTelescopio;
    private javax.swing.JLabel EtiquetaRequisitosArco;
    private javax.swing.JLabel EtiquetaRequisitosRed;
    private javax.swing.JLabel EtiquetaRequisitosTelescopio;
    private javax.swing.JLabel HiloHacha;
    private javax.swing.JLabel HiloHacha1;
    private javax.swing.JLabel HiloMartillo;
    private javax.swing.JLabel MaderaHacha;
    private javax.swing.JLabel MaderaHacha1;
    private javax.swing.JLabel MaderaMartillo;
    private javax.swing.JLabel PiedraHacha;
    private javax.swing.JLabel PiedraMartillo;
    private javax.swing.JLabel PiedraMartillo2;
    private javax.swing.JLabel Red;
    private javax.swing.JLabel Telescopio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
