/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteVentanas;

import javax.swing.JOptionPane;

/**
 *
 * @author MARTHA
 */
public class ConstruirHerramienta extends javax.swing.JFrame {
    int contadorPiedra=0,contadorCristal=0,contadorHilo=0,contadorMadera=0,contadorHacha=0,
            contadorMartillo=0,contadorArco=0, contadorTelescopio=0,contadorRed=0;
    /**
     * Creates new form ConstruirHerramienta
     */
    public ConstruirHerramienta(int piedra,int cristal,int hilo,int madera, int hacha, int martillo, int arco, int telescopio, int red) {
        contadorPiedra = piedra;
        contadorCristal=cristal;
        contadorHilo=hilo;
        contadorMadera=madera;
        contadorHacha=hacha;        
        contadorMartillo=martillo;
        contadorArco = arco;
        contadorTelescopio = telescopio;
        contadorRed = red;
        initComponents();
        setLocationRelativeTo(null);
    }

    public int getContadorMartillo() {
        return contadorMartillo;
    }

    public int getContadorHacha() {
        return contadorHacha;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EtiquetaConstruir = new javax.swing.JLabel();
        Martillo = new javax.swing.JLabel();
        EtiquetaRequisitosMartillo = new javax.swing.JLabel();
        PiedraMartillo = new javax.swing.JLabel();
        HiloMartillo = new javax.swing.JLabel();
        MaderaMartillo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CantidadMartillo = new javax.swing.JLabel();
        EtiquetaRequisitosHacha = new javax.swing.JLabel();
        PiedraHacha = new javax.swing.JLabel();
        HiloHacha = new javax.swing.JLabel();
        MaderaHacha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CantidadHacha = new javax.swing.JLabel();
        Hacha = new javax.swing.JLabel();
        BotonHacha = new javax.swing.JButton();
        BotonMartillo = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        EtiquetaConstruir.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EtiquetaConstruir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaConstruir.setText("Construir Herramienta");

        Martillo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Martillo.setText("Martillo");

        EtiquetaRequisitosMartillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaRequisitosMartillo.setText("Requisitos:");

        PiedraMartillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PiedraMartillo.setText("Piedra = 1");

        HiloMartillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HiloMartillo.setText("Hilo = 1");

        MaderaMartillo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaderaMartillo.setText("Madera = 2");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Cantidad: ");

        CantidadMartillo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadMartillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadMartillo.setText("0");
        if(contadorMartillo==0){
            CantidadMartillo.setText(""+(contadorMartillo));
        }else{
            CantidadMartillo.setText(""+(contadorMartillo));
        }

        EtiquetaRequisitosHacha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EtiquetaRequisitosHacha.setText("Requisitos:");

        PiedraHacha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        PiedraHacha.setText("Piedra = 1");

        HiloHacha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        HiloHacha.setText("Hilo = 1");

        MaderaHacha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MaderaHacha.setText("Madera = 2");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Cantidad: ");

        CantidadHacha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadHacha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadHacha.setText("0");
        if(contadorHacha==0){
            CantidadHacha.setText(""+(contadorHacha));
        }else{
            CantidadHacha.setText(""+(contadorHacha));
        }

        Hacha.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hacha.setText("Hacha");

        BotonHacha.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Hacha.jpg")); // NOI18N
        BotonHacha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonHachaMouseClicked(evt);
            }
        });

        BotonMartillo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Martillo.jpg")); // NOI18N
        BotonMartillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMartilloMouseClicked(evt);
            }
        });

        BotonRegresar.setBackground(new java.awt.Color(204, 204, 255));
        BotonRegresar.setText("Regresar");
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EtiquetaConstruir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(Martillo))
                        .addComponent(EtiquetaRequisitosMartillo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(PiedraMartillo)
                        .addComponent(HiloMartillo)
                        .addComponent(MaderaMartillo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CantidadMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BotonMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Hacha))
                    .addComponent(EtiquetaRequisitosHacha)
                    .addComponent(PiedraHacha)
                    .addComponent(HiloHacha)
                    .addComponent(MaderaHacha)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantidadHacha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonHacha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRegresar)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaConstruir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Martillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EtiquetaRequisitosMartillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PiedraMartillo)
                        .addGap(4, 4, 4)
                        .addComponent(HiloMartillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaderaMartillo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CantidadMartillo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Hacha)
                        .addGap(3, 3, 3)
                        .addComponent(BotonHacha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EtiquetaRequisitosHacha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PiedraHacha)
                        .addGap(4, 4, 4)
                        .addComponent(HiloHacha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaderaHacha)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CantidadHacha))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonRegresar)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        // TODO add your handling code here:
        
        MenuPrincipal ventana = new MenuPrincipal(contadorPiedra,contadorCristal,contadorMadera,contadorHilo,contadorArco,contadorMartillo,contadorHacha,contadorTelescopio,contadorRed);
        dispose();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_BotonRegresarMouseClicked

    private void BotonMartilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMartilloMouseClicked
        // TODO add your handling code here:
        
        if(contadorPiedra>=1 && contadorHilo>=1 && contadorMadera>=2){
            if(contadorMartillo>2){
                JOptionPane.showMessageDialog(null, "No puede Crear mas de tres martillos");
            }else{
                contadorPiedra-=1;
                contadorHilo-=1;
                contadorMadera-=1;
                contadorMartillo+=1;
                JOptionPane.showMessageDialog(null,"Martillo Creado");
            }

            CantidadMartillo.setText(""+contadorMartillo);
        }else{
            JOptionPane.showMessageDialog(null,"No tiene Requisitos suficientes para crear el Martillo");
        }
        
    }//GEN-LAST:event_BotonMartilloMouseClicked

    private void BotonHachaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHachaMouseClicked
        // TODO add your handling code here:
        if(contadorPiedra>=1 && contadorHilo>=1 && contadorMadera>=2){
            if(contadorHacha>2){
                JOptionPane.showMessageDialog(null, "No puede Crear mas de dos Hachas");
            }else{
                contadorPiedra-=1;
                contadorHilo-=1;
                contadorMadera-=1;
                contadorHacha+=1;
                JOptionPane.showMessageDialog(null,"Hacha Creado");
                
            }
            CantidadHacha.setText(""+contadorHacha);
        }else{
            JOptionPane.showMessageDialog(null,"No tiene Requisitos suficientes para crear la Hacha");
        }
        
    }//GEN-LAST:event_BotonHachaMouseClicked

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConstruirHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConstruirHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConstruirHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConstruirHerramienta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConstruirHerramienta(0,0,0,0,0,0,0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonHacha;
    private javax.swing.JButton BotonMartillo;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel CantidadHacha;
    private javax.swing.JLabel CantidadMartillo;
    private javax.swing.JLabel EtiquetaConstruir;
    private javax.swing.JLabel EtiquetaRequisitosHacha;
    private javax.swing.JLabel EtiquetaRequisitosMartillo;
    private javax.swing.JLabel Hacha;
    private javax.swing.JLabel HiloHacha;
    private javax.swing.JLabel HiloMartillo;
    private javax.swing.JLabel MaderaHacha;
    private javax.swing.JLabel MaderaMartillo;
    private javax.swing.JLabel Martillo;
    private javax.swing.JLabel PiedraHacha;
    private javax.swing.JLabel PiedraMartillo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
