/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteVentanas;

/**
 *
 * @author MARTHA
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    private int piedra=0,cristal=0,madera=0,hilo=0,arco=0,martillo=0,hacha=0,telescopio=0,red=0;
    private int hach,mart;
    boolean activadoRecolectar=true;
    /**
     * Creates new form MenuPrincipal
     * @param cPiedra
     * @param cCristal
     * @param cMadera
     * @param cHilo
     * @param cArco
     * @param cTelescopio
     * @param cMartillo
     * @param cHacha
     * @param cRed
     */
    public MenuPrincipal(int cPiedra,int cCristal,int cMadera,int cHilo,int cArco,int cMartillo,int cHacha,int cTelescopio,int cRed) {
        piedra=cPiedra;
        cristal=cCristal;
        madera = cMadera;
        hilo = cHilo;
        arco=cArco;
        martillo=cMartillo;
        
        hacha=cHacha;
        telescopio=cTelescopio;
        red = cRed;
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        EtiquetaMenu = new javax.swing.JLabel();
        EtiquetaRecolectar = new javax.swing.JLabel();
        BotonRecolectar = new javax.swing.JButton();
        EtiquetaConstruir = new javax.swing.JLabel();
        BotonConstruir = new javax.swing.JButton();
        EtiquetaFabricar = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        EtiquetaCantidad = new javax.swing.JLabel();
        BotonCantidad = new javax.swing.JButton();
        EtiquetaFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventario");
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonSalir.setBackground(new java.awt.Color(255, 102, 102));
        BotonSalir.setText("Salir");
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSalirMouseClicked(evt);
            }
        });
        jPanel1.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        EtiquetaMenu.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        EtiquetaMenu.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaMenu.setText("MENU");
        jPanel1.add(EtiquetaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 640, 60));

        EtiquetaRecolectar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EtiquetaRecolectar.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaRecolectar.setText("Recolectar Objetos");
        jPanel1.add(EtiquetaRecolectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        BotonRecolectar.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\RecolectarObjetos.jpg")); // NOI18N
        BotonRecolectar.setText("jButton1");
        BotonRecolectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRecolectarMouseClicked(evt);
            }
        });
        BotonRecolectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRecolectarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRecolectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 105, 110));

        EtiquetaConstruir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EtiquetaConstruir.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaConstruir.setText("Construir Herramienta");
        jPanel1.add(EtiquetaConstruir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        BotonConstruir.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\ConstruirHerramienta.jpg")); // NOI18N
        BotonConstruir.setText("jButton1");
        BotonConstruir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonConstruirMouseClicked(evt);
            }
        });
        jPanel1.add(BotonConstruir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 105, 110));

        EtiquetaFabricar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EtiquetaFabricar.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaFabricar.setText("Fabricar Arma");
        jPanel1.add(EtiquetaFabricar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\FabricarArma.jpg")); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 105, 110));

        EtiquetaCantidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EtiquetaCantidad.setForeground(new java.awt.Color(255, 255, 255));
        EtiquetaCantidad.setText("Ver Cantidad Objetos");
        jPanel1.add(EtiquetaCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        BotonCantidad.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\CantidadObjetos.jpg")); // NOI18N
        BotonCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCantidadMouseClicked(evt);
            }
        });
        jPanel1.add(BotonCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 120, 110));

        EtiquetaFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Fondo.jpg")); // NOI18N
        jPanel1.add(EtiquetaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void BotonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
        
    }//GEN-LAST:event_BotonSalirMouseClicked

    private void BotonRecolectarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRecolectarMouseClicked
        // TODO add your handling code here:
        
        /*if(activadoRecolectar=true){
        RecolectarObjetos recolectar = new RecolectarObjetos(0,0,0,0);
        
        dispose();
        
        recolectar.setVisible(true);
        activadoRecolectar=false;
        
        }else*/ if(activadoRecolectar){
            System.out.println(piedra);
            System.out.println(cristal);
            System.out.println(madera);
            System.out.println(hilo);
            RecolectarObjetos recolectar = new RecolectarObjetos(piedra,cristal,madera,hilo);
            dispose();
            recolectar.setVisible(true);
        }
    }//GEN-LAST:event_BotonRecolectarMouseClicked

    private void BotonRecolectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRecolectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRecolectarActionPerformed

    private void BotonConstruirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonConstruirMouseClicked
        // TODO add your handling code here:
        dispose();
            
            
            ConstruirHerramienta construir = new ConstruirHerramienta(piedra,cristal,hilo,madera,hacha,martillo,arco,telescopio,red);
            hach= construir.getContadorHacha();
            mart = construir.getContadorMartillo();
            ConstruirHerramienta construir2 = new ConstruirHerramienta(piedra,cristal,hilo,madera,hach,mart,arco,telescopio,red);
            construir2.setVisible(true);        
        

        
        
        
    }//GEN-LAST:event_BotonConstruirMouseClicked

    private void BotonCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCantidadMouseClicked
        // TODO add your handling code here:
        
        VentanaCantidadObjetos cantidad = new VentanaCantidadObjetos(piedra,cristal,hilo,madera,arco,martillo,hacha,telescopio,red);
        dispose();
        cantidad.setVisible(true);
        
    }//GEN-LAST:event_BotonCantidadMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        ConstruirArma arma = new ConstruirArma(piedra,cristal,hilo,madera,hacha,martillo,arco,telescopio,red);
        dispose();
        arma.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(0,0,0,0,0,0,0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCantidad;
    private javax.swing.JButton BotonConstruir;
    private javax.swing.JButton BotonRecolectar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel EtiquetaCantidad;
    private javax.swing.JLabel EtiquetaConstruir;
    private javax.swing.JLabel EtiquetaFabricar;
    private javax.swing.JLabel EtiquetaFondo;
    private javax.swing.JLabel EtiquetaMenu;
    private javax.swing.JLabel EtiquetaRecolectar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
