/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteVentanas;

import javax.swing.JOptionPane;

/**
 *
 * @author MARTHA
 */
public class RecolectarObjetos extends javax.swing.JFrame {
    String cantidadesP, cantidadesM, cantidadesC,cantidadesH;
    private int contadorPiedra,contadorMadera,contadorCristal,contadorHilo;
    
    /**
     * Creates new form RecolectarObjetos
     */
    public RecolectarObjetos(int piedra,int madera,int cristal, int hilo) {
        
        contadorPiedra=piedra;
        contadorMadera = madera;
        contadorCristal = cristal;
        contadorHilo = hilo;
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EtiquetaTitulo = new javax.swing.JLabel();
        BotonPiedra = new javax.swing.JButton();
        BotonMadera = new javax.swing.JButton();
        BotonCristal = new javax.swing.JButton();
        BotonHilo = new javax.swing.JButton();
        CantidadPiedra = new javax.swing.JLabel();
        CantidadMadera = new javax.swing.JLabel();
        CantidadCristal = new javax.swing.JLabel();
        CantidadHilo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recolectar Objetos");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        EtiquetaTitulo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        EtiquetaTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiquetaTitulo.setText("RecolectarObjetos");

        BotonPiedra.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Piedra.jpg")); // NOI18N
        BotonPiedra.setText("jButton1");
        BotonPiedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonPiedraMouseClicked(evt);
            }
        });

        BotonMadera.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Madera.jpg")); // NOI18N
        BotonMadera.setText("jButton1");
        BotonMadera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMaderaMouseClicked(evt);
            }
        });
        BotonMadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMaderaActionPerformed(evt);
            }
        });

        BotonCristal.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Cristal.jpg")); // NOI18N
        BotonCristal.setText("jButton1");
        BotonCristal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCristalMouseClicked(evt);
            }
        });

        BotonHilo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Hilo.jpg")); // NOI18N
        BotonHilo.setText("jButton1");
        BotonHilo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonHiloMouseClicked(evt);
            }
        });

        CantidadPiedra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadPiedra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadPiedra.setText("0");
        if(contadorPiedra==0){
            CantidadPiedra.setText(""+(contadorPiedra));
        }else{
            CantidadPiedra.setText(""+(contadorPiedra-1));
        }

        CantidadMadera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadMadera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadMadera.setText("0");
        if(contadorMadera==0){
            CantidadMadera.setText(""+(contadorMadera));
        }else{
            CantidadMadera.setText(""+(contadorMadera-1));
        }

        CantidadCristal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadCristal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadCristal.setText("0");
        if(contadorCristal==0){
            CantidadCristal.setText(""+(contadorCristal));
        }else{
            CantidadCristal.setText(""+(contadorCristal-1));
        }

        CantidadHilo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CantidadHilo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadHilo.setText("0");
        if(contadorHilo==0){
            CantidadHilo.setText(""+(contadorHilo));
        }else{
            CantidadHilo.setText(""+(contadorHilo-1));
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EtiquetaTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantidadPiedra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantidadMadera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BotonCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantidadCristal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CantidadHilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonHilo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiquetaTitulo)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadPiedra)
                    .addComponent(CantidadMadera))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonHilo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadCristal)
                    .addComponent(CantidadHilo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPiedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonPiedraMouseClicked
        // TODO add your handling code here:
        
        
        cantidadesP = String.valueOf(contadorPiedra);
        if(contadorPiedra<=4){
            CantidadPiedra.setText(cantidadesP);
            contadorPiedra++;
        }else{
            JOptionPane.showMessageDialog(null,"No puede tener mas de 4 objetos de Piedra");
        }
        
    }//GEN-LAST:event_BotonPiedraMouseClicked

    private void BotonMaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMaderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonMaderaActionPerformed

    private void BotonMaderaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMaderaMouseClicked
        // TODO add your handling code here:
        cantidadesM = String.valueOf(contadorMadera);
        if(contadorMadera<=4){
            CantidadMadera.setText(cantidadesM);
            contadorMadera++;
        }else{
            JOptionPane.showMessageDialog(null,"No puede tener mas de 4 objetos de Madera");
        }
        
    }//GEN-LAST:event_BotonMaderaMouseClicked

    private void BotonCristalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCristalMouseClicked
        // TODO add your handling code here:
        
        
        cantidadesC = String.valueOf(contadorCristal);
        if(contadorCristal<=4){
            CantidadCristal.setText(cantidadesC);
            contadorCristal++;
        }else{
            JOptionPane.showMessageDialog(null,"No puede tener mas de 4 objetos de Cristal");
        }
        
    }//GEN-LAST:event_BotonCristalMouseClicked

    private void BotonHiloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHiloMouseClicked
        // TODO add your handling code here:
        
        
        cantidadesH = String.valueOf(contadorHilo);
        if(contadorHilo<=9){
            CantidadHilo.setText(cantidadesH);
            contadorHilo++;
        }else{
            JOptionPane.showMessageDialog(null,"No puede tener mas de 9 objetos de Hilo");
        }
        
    }//GEN-LAST:event_BotonHiloMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        MenuPrincipal ventana = new MenuPrincipal(contadorPiedra,contadorCristal,contadorMadera,contadorHilo,0,0,0,0,0);
        dispose();
        ventana.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    public int getContadorPiedra() {
        return contadorPiedra;
    }

    public int getContadorMadera() {
        return contadorMadera;
    }

    public int getContadorCristal() {
        return contadorCristal;
    }

    public int getContadorHilo() {
        return contadorHilo;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecolectarObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecolectarObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecolectarObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecolectarObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecolectarObjetos(0,0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCristal;
    private javax.swing.JButton BotonHilo;
    private javax.swing.JButton BotonMadera;
    private javax.swing.JButton BotonPiedra;
    private javax.swing.JLabel CantidadCristal;
    private javax.swing.JLabel CantidadHilo;
    private javax.swing.JLabel CantidadMadera;
    private javax.swing.JLabel CantidadPiedra;
    private javax.swing.JLabel EtiquetaTitulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
