/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PaqueteVentanas;

/**
 *
 * @author MARTHA
 */
public class VentanaCantidadObjetos extends javax.swing.JFrame {
    int contadorPiedra=0,contadorCristal=0,contadorHilo=0,contadorMadera=0,contadorArco=0,contadorHacha=0,contadorTelescopio=0,
            contadorMartillo=0,contadorRed=0;
    /**
     * Creates new form VentanaCantidadObjetos
     */
    public VentanaCantidadObjetos(int piedra,int cristal,int hilo,int madera, int arco, int martillo, int hacha, int telescopio, int red) {
        contadorPiedra = piedra;
        contadorCristal=cristal;
        contadorHilo=hilo;
        contadorMadera=madera;
        contadorArco=arco;        
        contadorHacha=hacha;        
        contadorTelescopio=telescopio;        
        contadorMartillo=martillo;
        contadorRed=red;  
        
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void mostrarCantidad (){
        
        EtiquetaPiedra.setText(String.valueOf(contadorPiedra));
        EtiquetaCristal.setText(String.valueOf(contadorCristal));
        EtiquetaHilo.setText(String.valueOf(contadorHilo));
        EtiquetaMadera.setText(String.valueOf(contadorMadera));
        EtiquetaArco.setText(String.valueOf(contadorArco));
        EtiquetaHacha.setText(String.valueOf(contadorHacha));
        EtiquetaTelescopio.setText(String.valueOf(contadorTelescopio));
        EtiquetaMartillo.setText(String.valueOf(contadorMartillo));
        EtiquetaRed.setText(String.valueOf(contadorRed));
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EtiquetaPiedra = new javax.swing.JLabel();
        CantidadPiedra = new javax.swing.JLabel();
        EtiquetaCristal = new javax.swing.JLabel();
        CantidadCristal = new javax.swing.JLabel();
        EtiquetaHilo = new javax.swing.JLabel();
        CantidadHilo = new javax.swing.JLabel();
        EtiquetaMadera = new javax.swing.JLabel();
        CantidadMadera = new javax.swing.JLabel();
        EtiquetaArco = new javax.swing.JLabel();
        CantidadArco = new javax.swing.JLabel();
        EtiquetaMartillo = new javax.swing.JLabel();
        CantidadMartillo = new javax.swing.JLabel();
        EtiquetaHacha = new javax.swing.JLabel();
        CantidadHacha = new javax.swing.JLabel();
        EtiquetaTelescopio = new javax.swing.JLabel();
        CantidadTelescopio = new javax.swing.JLabel();
        EtiquetaRed = new javax.swing.JLabel();
        CantidadRed = new javax.swing.JLabel();
        BotonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Panel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cantidad Objetos");

        EtiquetaPiedra.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Piedra.jpg")); // NOI18N

        CantidadPiedra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadPiedra.setText("0");
        if(contadorPiedra==0){
            CantidadPiedra.setText(""+(contadorPiedra));
        }else{
            CantidadPiedra.setText(""+(contadorPiedra-1));
        }

        EtiquetaCristal.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Cristal.jpg")); // NOI18N

        CantidadCristal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadCristal.setText("0");
        if(contadorCristal==0){
            CantidadCristal.setText(""+(contadorCristal));
        }else{
            CantidadCristal.setText(""+(contadorCristal-1));
        }

        EtiquetaHilo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Hilo.jpg")); // NOI18N

        CantidadHilo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadHilo.setText("0");
        if(contadorHilo==0){
            CantidadHilo.setText(""+(contadorHilo));
        }else{
            CantidadHilo.setText(""+(contadorHilo-1));
        }

        EtiquetaMadera.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Madera.jpg")); // NOI18N

        CantidadMadera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadMadera.setText("0");
        if(contadorMadera==0){
            CantidadMadera.setText(""+(contadorMadera));
        }else{
            CantidadMadera.setText(""+(contadorMadera-1));
        }

        EtiquetaArco.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Arco.jpg")); // NOI18N

        CantidadArco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadArco.setText("0");

        CantidadArco.setText(""+(contadorArco));

        EtiquetaMartillo.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Martillo.jpg")); // NOI18N
        EtiquetaMartillo.setText("jLabel2");

        CantidadMartillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadMartillo.setText("0");
        CantidadMartillo.setText(""+(contadorMartillo));

        EtiquetaHacha.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Hacha.jpg")); // NOI18N
        EtiquetaHacha.setText("jLabel2");

        CantidadHacha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadHacha.setText("0");

        CantidadHacha.setText(""+(contadorHacha));

        EtiquetaTelescopio.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Red.jpg")); // NOI18N
        EtiquetaTelescopio.setText("jLabel2");

        CantidadTelescopio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadTelescopio.setText("0");

        CantidadTelescopio.setText(""+(contadorTelescopio));

        EtiquetaRed.setIcon(new javax.swing.ImageIcon("C:\\Users\\MARTHA\\Documents\\NetBeansProjects\\InterfazInventario\\src\\main\\java\\Imagenes\\Telescopio.jpg")); // NOI18N
        EtiquetaRed.setText("jLabel2");

        CantidadRed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CantidadRed.setText("0");

        CantidadRed.setText(""+(contadorRed));

        BotonRegresar.setText("Regresar");
        BotonRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(EtiquetaPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EtiquetaMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EtiquetaCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EtiquetaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadCristal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CantidadArco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(EtiquetaMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EtiquetaHilo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CantidadMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CantidadHilo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EtiquetaHacha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadHacha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CantidadTelescopio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtiquetaTelescopio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotonRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EtiquetaRed, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CantidadRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 28, Short.MAX_VALUE))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(EtiquetaHilo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CantidadHilo))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(EtiquetaCristal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CantidadCristal))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(EtiquetaPiedra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CantidadPiedra)))
                .addGap(31, 31, 31)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EtiquetaArco, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EtiquetaMartillo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantidadMartillo))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(EtiquetaMadera, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CantidadMadera)
                            .addComponent(CantidadArco))))
                .addGap(18, 18, 18)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EtiquetaTelescopio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EtiquetaRed, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CantidadTelescopio)
                            .addComponent(CantidadRed)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(EtiquetaHacha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CantidadHacha)))
                .addGap(18, 18, 18)
                .addComponent(BotonRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegresarMouseClicked
        // TODO add your handling code here:
        
        MenuPrincipal ventana = new MenuPrincipal(contadorPiedra,contadorCristal,contadorMadera,contadorHilo,contadorArco,contadorMartillo,contadorHacha,contadorTelescopio,contadorRed);
        dispose();
        ventana.setVisible(true);
        
    }//GEN-LAST:event_BotonRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCantidadObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCantidadObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCantidadObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCantidadObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCantidadObjetos(0,0,0,0,0,0,0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JLabel CantidadArco;
    private javax.swing.JLabel CantidadCristal;
    private javax.swing.JLabel CantidadHacha;
    private javax.swing.JLabel CantidadHilo;
    private javax.swing.JLabel CantidadMadera;
    private javax.swing.JLabel CantidadMartillo;
    private javax.swing.JLabel CantidadPiedra;
    private javax.swing.JLabel CantidadRed;
    private javax.swing.JLabel CantidadTelescopio;
    private javax.swing.JLabel EtiquetaArco;
    private javax.swing.JLabel EtiquetaCristal;
    private javax.swing.JLabel EtiquetaHacha;
    private javax.swing.JLabel EtiquetaHilo;
    private javax.swing.JLabel EtiquetaMadera;
    private javax.swing.JLabel EtiquetaMartillo;
    private javax.swing.JLabel EtiquetaPiedra;
    private javax.swing.JLabel EtiquetaRed;
    private javax.swing.JLabel EtiquetaTelescopio;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
